<?php
$this->load->view('template/header');
$this->load->view('home/navbar');
$this->load->view('home/header');
$this->load->view('home/topic');
$this->load->view('home/book');
$this->load->view('home/about');
$this->load->view('home/footer');
$this->load->view('template/footer');
?>